//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoLoginApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    [Bind(Exclude="iId")]
    public partial class tbl_RegisterUser
    {
       [ScaffoldColumn(false)]
        [Key]
        public int iId { get; set; }

        [Required(ErrorMessage="Please enter User Name !!!")]
       [Display(Name="User Name :")]
        [StringLength(30,ErrorMessage="User name must be thirty charter long.")]
        public string sUserName { get; set; }

        [Required(ErrorMessage="Enter Email Adress !!!")]
        [EmailAddress(ErrorMessage="Please Enter valid Email Id")]
        [Display(Name="Email Adress :")]
        public string sEmail { get; set; }

        [Required(ErrorMessage="Please Enter Password")]
        [Display(Name="Password :")]
        [StringLength(9,ErrorMessage="Password must be nine character long.")]
        public string sPassword { get; set; }

        [Required(ErrorMessage="Please Enter Phone Number")]
        [Display(Name="Phone Number :")]
        [StringLength(10,ErrorMessage="Phone number must be 10 digit")]
        public string sPhoneNumber { get; set; }
    }
}
